set_property IOSTANDARD LVCMOS33 [get_ports {row[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {row[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {row[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {row[3]}]
set_property PULLUP true [get_ports {row[0]}]
set_property PULLUP true [get_ports {row[1]}]
set_property PULLUP true [get_ports {row[2]}]
set_property PULLUP true [get_ports {row[3]}]
set_property PACKAGE_PIN B17 [get_ports {row[3]}]
set_property PACKAGE_PIN B16 [get_ports {row[2]}]
set_property PACKAGE_PIN A16 [get_ports {row[1]}]
set_property PACKAGE_PIN A15 [get_ports {row[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {col[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {col[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {col[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {col[3]}]
set_property PACKAGE_PIN F14 [get_ports {col[3]}]
set_property PACKAGE_PIN F13 [get_ports {col[2]}]
set_property PACKAGE_PIN B14 [get_ports {col[1]}]
set_property PACKAGE_PIN B13 [get_ports {col[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {duan[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {duan[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {duan[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {duan[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {duan[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {duan[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {duan[6]}]
set_property PACKAGE_PIN D4 [get_ports {duan[6]}]
set_property PACKAGE_PIN E3 [get_ports {duan[5]}]
set_property PACKAGE_PIN D3 [get_ports {duan[4]}]
set_property PACKAGE_PIN F4 [get_ports {duan[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {wei[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {wei[1]}]
set_property PACKAGE_PIN G6 [get_ports {wei[0]}]
set_property PACKAGE_PIN P17 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property PACKAGE_PIN F3 [get_ports {duan[2]}]
set_property PACKAGE_PIN E2 [get_ports {duan[1]}]
set_property PACKAGE_PIN D2 [get_ports {duan[0]}]


set_property IOSTANDARD LVCMOS33 [get_ports {wei[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {wei[2]}]
set_property PACKAGE_PIN G1 [get_ports {wei[3]}]
set_property PACKAGE_PIN F1 [get_ports {wei[2]}]
set_property PACKAGE_PIN E1 [get_ports {wei[1]}]


set_property PACKAGE_PIN P15 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports rst]


set_property PACKAGE_PIN M4 [get_ports changePass]
set_property PACKAGE_PIN N4 [get_ports clearPass]
set_property PACKAGE_PIN R1 [get_ports confirmPass]
set_property IOSTANDARD LVCMOS33 [get_ports changePass]
set_property IOSTANDARD LVCMOS33 [get_ports clearPass]
set_property IOSTANDARD LVCMOS33 [get_ports confirmPass]


set_property PACKAGE_PIN F6 [get_ports lock]
set_property PACKAGE_PIN G4 [get_ports unlock]
set_property PACKAGE_PIN K3 [get_ports beef]
set_property IOSTANDARD LVCMOS33 [get_ports beef]
set_property IOSTANDARD LVCMOS33 [get_ports unlock]
set_property IOSTANDARD LVCMOS33 [get_ports lock]
